version: "3.9"
services:
  wol:
    build: .
    image: wol
    container_name: wol
    network_mode: host

  tunnel:
    image: erisamoe/cloudflared
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
